CREATE TYPE "DomainStatus" AS ENUM ('PENDING', 'VERIFIED', 'FAILED');
CREATE TYPE "DiscountType" AS ENUM ('PERCENTAGE', 'FIXED');
CREATE TYPE "NotificationEvent" AS ENUM ('ORDER_CREATED', 'ORDER_PAID', 'ORDER_SHIPPED', 'CART_ABANDONED');
CREATE TYPE "AnalyticsEventType" AS ENUM ('STOREFRONT_VIEW', 'PRODUCT_VIEW', 'ADD_TO_CART', 'CHECKOUT_STARTED');

ALTER TABLE "Cart" ADD COLUMN "abandonedAt" TIMESTAMP(3), ADD COLUMN "recoveredAt" TIMESTAMP(3), ADD COLUMN "recoveryEmail" TEXT, ADD COLUMN "recoveryTokenHash" TEXT;
ALTER TABLE "CartItem" ADD COLUMN "variantId" TEXT;
ALTER TABLE "Order" ADD COLUMN "couponCode" TEXT, ADD COLUMN "discountInCents" INTEGER NOT NULL DEFAULT 0, ADD COLUMN "shippingInCents" INTEGER NOT NULL DEFAULT 0, ADD COLUMN "shippingMethod" TEXT, ADD COLUMN "shippingPostalCode" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN "variantName" TEXT;
ALTER TABLE "StoreSettings" ADD COLUMN "announcement" TEXT, ADD COLUMN "borderRadius" TEXT NOT NULL DEFAULT 'MEDIUM', ADD COLUMN "fontFamily" TEXT NOT NULL DEFAULT 'SYSTEM', ADD COLUMN "secondaryColor" TEXT NOT NULL DEFAULT '#292524', ADD COLUMN "showPoweredBy" BOOLEAN NOT NULL DEFAULT true;

CREATE TABLE "ProductVariant" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "productId" TEXT NOT NULL, "sku" TEXT NOT NULL, "name" TEXT NOT NULL, "options" JSONB NOT NULL, "priceInCents" INTEGER NOT NULL, "stock" INTEGER NOT NULL DEFAULT 0, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ProductVariant_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CustomDomain" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "hostname" TEXT NOT NULL, "status" "DomainStatus" NOT NULL DEFAULT 'PENDING', "verificationToken" TEXT NOT NULL, "verifiedAt" TIMESTAMP(3), "lastCheckedAt" TIMESTAMP(3), "failureReason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CustomDomain_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Coupon" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "type" "DiscountType" NOT NULL, "value" INTEGER NOT NULL, "minimumInCents" INTEGER NOT NULL DEFAULT 0, "maximumUses" INTEGER, "usedCount" INTEGER NOT NULL DEFAULT 0, "startsAt" TIMESTAMP(3), "endsAt" TIMESTAMP(3), "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Coupon_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ShippingZone" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "name" TEXT NOT NULL, "postalPrefixes" TEXT[] DEFAULT ARRAY[]::TEXT[], "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ShippingZone_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ShippingMethod" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "shippingZoneId" TEXT NOT NULL, "name" TEXT NOT NULL, "priceInCents" INTEGER NOT NULL, "estimatedDays" INTEGER, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ShippingMethod_pkey" PRIMARY KEY ("id"));
CREATE TABLE "NotificationRule" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "event" "NotificationEvent" NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "subject" TEXT NOT NULL, "message" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "NotificationRule_pkey" PRIMARY KEY ("id"));
CREATE TABLE "NotificationLog" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "event" "NotificationEvent" NOT NULL, "recipient" TEXT NOT NULL, "status" "NotificationStatus" NOT NULL DEFAULT 'PENDING', "error" TEXT, "sentAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "NotificationLog_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AnalyticsEvent" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "type" "AnalyticsEventType" NOT NULL, "productId" TEXT, "sessionId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AnalyticsEvent_pkey" PRIMARY KEY ("id"));

CREATE INDEX "ProductVariant_tenantId_productId_active_idx" ON "ProductVariant"("tenantId", "productId", "active"); CREATE UNIQUE INDEX "ProductVariant_tenantId_sku_key" ON "ProductVariant"("tenantId", "sku"); CREATE UNIQUE INDEX "ProductVariant_tenantId_id_key" ON "ProductVariant"("tenantId", "id");
CREATE UNIQUE INDEX "CustomDomain_hostname_key" ON "CustomDomain"("hostname"); CREATE UNIQUE INDEX "CustomDomain_verificationToken_key" ON "CustomDomain"("verificationToken"); CREATE INDEX "CustomDomain_tenantId_status_idx" ON "CustomDomain"("tenantId", "status");
CREATE INDEX "Coupon_tenantId_active_idx" ON "Coupon"("tenantId", "active"); CREATE UNIQUE INDEX "Coupon_tenantId_code_key" ON "Coupon"("tenantId", "code"); CREATE UNIQUE INDEX "Coupon_tenantId_id_key" ON "Coupon"("tenantId", "id");
CREATE INDEX "ShippingZone_tenantId_active_idx" ON "ShippingZone"("tenantId", "active"); CREATE UNIQUE INDEX "ShippingZone_tenantId_name_key" ON "ShippingZone"("tenantId", "name"); CREATE UNIQUE INDEX "ShippingZone_tenantId_id_key" ON "ShippingZone"("tenantId", "id");
CREATE INDEX "ShippingMethod_tenantId_shippingZoneId_active_idx" ON "ShippingMethod"("tenantId", "shippingZoneId", "active"); CREATE UNIQUE INDEX "ShippingMethod_tenantId_id_key" ON "ShippingMethod"("tenantId", "id");
CREATE INDEX "NotificationRule_tenantId_active_idx" ON "NotificationRule"("tenantId", "active"); CREATE UNIQUE INDEX "NotificationRule_tenantId_event_key" ON "NotificationRule"("tenantId", "event");
CREATE INDEX "NotificationLog_tenantId_event_createdAt_idx" ON "NotificationLog"("tenantId", "event", "createdAt"); CREATE INDEX "AnalyticsEvent_tenantId_type_createdAt_idx" ON "AnalyticsEvent"("tenantId", "type", "createdAt"); CREATE INDEX "AnalyticsEvent_tenantId_productId_createdAt_idx" ON "AnalyticsEvent"("tenantId", "productId", "createdAt"); CREATE UNIQUE INDEX "Cart_recoveryTokenHash_key" ON "Cart"("recoveryTokenHash"); CREATE INDEX "CartItem_tenantId_variantId_idx" ON "CartItem"("tenantId", "variantId");

ALTER TABLE "ProductVariant" ADD CONSTRAINT "ProductVariant_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProductVariant" ADD CONSTRAINT "ProductVariant_tenantId_productId_fkey" FOREIGN KEY ("tenantId", "productId") REFERENCES "Product"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CartItem" ADD CONSTRAINT "CartItem_tenantId_variantId_fkey" FOREIGN KEY ("tenantId", "variantId") REFERENCES "ProductVariant"("tenantId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CustomDomain" ADD CONSTRAINT "CustomDomain_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Coupon" ADD CONSTRAINT "Coupon_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ShippingZone" ADD CONSTRAINT "ShippingZone_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ShippingMethod" ADD CONSTRAINT "ShippingMethod_tenantId_shippingZoneId_fkey" FOREIGN KEY ("tenantId", "shippingZoneId") REFERENCES "ShippingZone"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NotificationRule" ADD CONSTRAINT "NotificationRule_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NotificationLog" ADD CONSTRAINT "NotificationLog_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AnalyticsEvent" ADD CONSTRAINT "AnalyticsEvent_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
