ALTER TABLE "NotificationLog"
ADD COLUMN "subject" TEXT NOT NULL DEFAULT '',
ADD COLUMN "message" TEXT NOT NULL DEFAULT '',
ADD COLUMN "actionUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN "attempts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "nextAttemptAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "lockedAt" TIMESTAMP(3),
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX "NotificationLog_status_nextAttemptAt_idx"
ON "NotificationLog"("status", "nextAttemptAt");
